### ISSUE TITLE
Clicking check under the settings produces an error

### ISSUE THREAD

**Issue by trsmith78** [nzbgetcom/Extension-Completion#9]
I do have python installed.
Executing script Completion with command CheckQue ue Completion: Could not start script Completion wit h command CheckQueue: Access is denied 
Completion: Could not find file C:/Users/troyd/AppData/Local/Programs/Python/Python311/ Script Completion with command CheckQueue failed

**Comment by liv-mrr** [comment]
@trsmith78 I've repeated your case and couldn't reproduce the problem.
Is Python shown on the STATUS page? Do other extensions work?
Could you provide more details, please?

**Comment by trsmith78** [comment]
I'm wondering if it's because I'm running on windows 11.
I installed it from the executable.  Version 24.4 stable 

From status screen:
Tools        Version     Path
Python     N/A            Not found

7-Zip         23.01        C:\Program Files\NZBGet\7za.exe

UnRAR     7.00          C:\Program Files\NZBGet\unrar.exe 

I would imagine a lot of people use Linux or docker.  

I haven't used any other extensions.  So I don't know if they work.

What else do you need to know?

**Comment by liv-mrr** [comment]
That means that NZBGet can't find Python, so extensions won't work.
You can use ShellOverride to enter your path to Python manually (go to Settings -> EXTENSION SCRIPTS -> ShellOverride) Don't forget the dot in **.py**=C:\Path\To\Python\python.exe

Could your OS detect Python?

**Comment by trsmith78** [comment]
Yes, python works fine for my other applications.  I wonder if I need to edit the environment variables?
I'll try to set the path manually in nzbget as you suggested.  Let you know.
Thank you!

**Comment by trsmith78** [comment]
Adding this as you suggested fix the issue.


.py=C:/Users/troyd/AppData/Local/Programs/Python/Python311/python.exe

Many thanks!!!
